sonar.projectKey=RandomCodeSpace_qctx
sonar.organization=randomcodespace

sonar.sources=.
sonar.exclusions=**/*_test.go,**/test/**,**/vendor/**,**/docs/**,**/bin/**,**/dist/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
